<div class="uk-section uk-section-xsmall uk-section-muted">
	<div class="uk-container" >
		<div class="uk-card uk-card-default uk-card-small uk-card-body">
			<div class='uk-child-width-expand uk-grid-small uk-text-left' uk-grid>
				<div class='uk-width-1-4'><div><span class='uk-text-bold'>System:</span></div></div>
				<div><span class='uk-label' id='lock_0'>Unknown</span></div>
				<div><button id="button_lock" class="uk-button uk-button-default uk-button-small" onclick="lock()">Lock</button></div>
			</div>
			<div class='uk-child-width-expand uk-grid-small uk-text-left' uk-grid>
				<div class='uk-width-1-4'><div><span class='uk-text-bold'>Player:</span></div></div>
				<div><span  class='uk-label' id='player'>Unknown</span></div>
				<div id="button_stop" style="visibility: hidden"><button class="uk-button uk-button-danger uk-button-small" onclick="stop()">Stop</button></div>
			</div>
		</div>
	</div>
</div>
