#ifndef __EPI_VERSION__
#define __EPI_VERSION__
// These variables are autogenerated and compiled
// into the library by the version.cmake script

namespace pml
{
    namespace epi
    {
        extern const char* GIT_TAG;
		extern const char* GIT_REV;
		extern const char* GIT_BRANCH;
	    extern const char* GIT_DATE;
	    extern unsigned long VERSION_MAJOR;
		extern unsigned long VERSION_MINOR;
		extern unsigned long VERSION_PATCH;
		extern const char* VERSION_STRING;
    }
}

#endif
